N = 128;
x1 = ones(1, 4);
x2 = ones(1, 6);
n1 = length(x1);
n2 = length(x2);
x1 = [x1, zeros(1, N - n1)];
x2 = [x2, zeros(1, N - n2)];
n = 0 : N - 1;
k = 0 : N - 1;
w = 2 * pi * k / N;
X1 = fft(x1);
X2 = fft(x2);
figure(1);
subplot(211);
stem(w, abs(X1), 'filled');
xlim([0 2 * pi]);
xlabel('w');
ylabel('Magnitude');
title('128 - point DFT of x1');
subplot(212);
stem(w, abs(X2), 'filled');
xlim([0 2 * pi]);
xlabel('w');
ylabel('Magnitude');
title('128 - point DFT of x2');
X3 = 1 / N * cconv(X1, X2, N);
x4 = x1 .* x2;
X4 = fft(x4);
figure(2);
subplot(211);
stem(w, abs(X3), 'filled');
xlim([0 2 * pi]);
xlabel('w');
ylabel('Magnitude');
title('Circular Convolution of DFTs of x1 and x2');
subplot(212);
stem(w, abs(X4), 'filled');
xlim([0 2 * pi]);
xlabel('w');
ylabel('Magnitude');
title('DFT of multiplication of x1 and x2');
